### ISSUE TITLE
Broken non-Linux path

### ISSUE THREAD

**Issue by Freaky** [joshtriplett/io-mux#4]
Did you test this? :P

```
error[E0308]: mismatched types
   --> src/lib.rs:211:35
    |
211 |             let bytes = self.recv(self.buf, libc::MSG_PEEK)?;
    |                                   ^^^^^^^^
    |                                   |
    |                                   expected `&mut [u8]`, found struct `std::vec::Vec`
    |                                   help: consider mutably borrowing here: `&mut self.buf`
    |
    = note: expected mutable reference `&mut [u8]`
                          found struct `std::vec::Vec<u8>`

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
   --> src/lib.rs:219:24
    |
219 |                 return Ok(&self.buf[..bytes], addr);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error: aborting due to 2 previous errors
```

And of course you can't mutably borrow the buffer because you're also trying to mutably borrow its parent struct in the recv.

**Comment by joshtriplett** [comment]
@Freaky I did compile-test it, but evidently not after the last round of changes. My apologies. I'll upload a fix today.

I also need to add a feature flag to test the non-Linux path on Linux, so that I can run `cargo test --features test_portable_path_on_linux` or similar.

**Comment by joshtriplett** [comment]
I've merged your fix, thank you!

I've also added the `test-portable` feature flag to test the portable path even on Linux, which should hopefully prevent this from happening again.
