### ISSUE TITLE
Output order is not guaranteed

### ISSUE THREAD

**Issue by mqudsi** [joshtriplett/io-mux#6]
As I commented on r/rust, while the output from a unix socket is guaranteed to be FIFO, the kernel does not make any guarantees about the order from which the various write ends will be read from when muxing into the read socket. You are merely relegating the select/poll process to the kernel, but not fundamentally changing the situation.

The following code should prove what I'm saying; as you can see, the kernel does not magically known when to stop reading from a socket/pipe/fd and may interleave output *out of order* from the different writers.

```rust
use chrono::Utc;
use std::io::prelude::*;

fn main() {
    if let Err(e) = run() {
        eprintln!("{:?}", e);
    }
}

fn run() -> Result<(), std::io::Error> {
    let mut mux = io_mux::Mux::new()?;

    let mut write1 = mux.make_tagged_sender("stdout").unwrap();
    let mut write2 = mux.make_tagged_sender("stderr").unwrap();

    {
        std::thread::spawn(move || loop {
            write!(write1, "{}", Utc::now().to_rfc3339()).unwrap();
            write1.flush();
        });
    }

    {
        std::thread::spawn(move || loop {
            write!(write2, "{}", Utc::now().to_rfc3339()).unwrap();
            write2.flush();
        });
    }

    let mut previous_timestamp = chrono::MIN_DATE.and_hms(0, 0, 0);
    loop {
        let data = mux.read()?;
        let text = std::str::from_utf8(data.data).unwrap();
        let timestamp = chrono::DateTime::parse_from_rfc3339(text).unwrap().into();
        assert!(timestamp > previous_timestamp);
        previous_timestamp = timestamp;
        println!(
            "{}: {}",
            data.tag.unwrap(),
            std::str::from_utf8(data.data).unwrap()
        );
    }
}
```

which fails very quickly:

```
stderr: 2020-02-06T17:58:20.390367405+00:00
stderr: 2020-02-06T17:58:20.390505623+00:00
thread 'main' panicked at 'assertion failed: timestamp >= previous_timestamp', src/main.rs:42:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', src/main.rs:31:17
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }', src/main.rs:22:17
```

As you can see, it kept reading from `stderr` past the first flush even though `stdout` had generated data before it.

EDIT: Removed mutex because it's besides the point.

**Comment by uberjay** [comment]
I *think* you're conflating two things, but could be wrong. Your demo program is inherently racy so we shouldn't expect the timestamps to be in order regardless of the scheme used by io-mux.

I've added a "log" -- an in-memory VecDeque which I think we would all agree is able to maintain order of insertion:
```rust
use chrono::Utc;
use std::collections::VecDeque;
use std::io::prelude::*;
use std::sync::{Arc, Mutex};

fn main() {
    if let Err(e) = run() {
        eprintln!("{:?}", e);
    }
}

fn run() -> Result<(), std::io::Error> {
    let log = Arc::new(Mutex::new(VecDeque::<String>::new()));
    let mut mux = io_mux::Mux::new()?;

    let log1 = log.clone();
    let mut write1 = mux.make_tagged_sender("stdout").unwrap();
    let log2 = log.clone();
    let mut write2 = mux.make_tagged_sender("stderr").unwrap();

    {
        std::thread::spawn(move || {
            for _ in 0..20 {
                let s = format!("{}", Utc::now().to_rfc3339());
                let mut l = log1.lock().unwrap();
                write!(write1, "{}", s).unwrap();
                write1.flush().unwrap();
                l.push_back(s);
            }
        });
    }

    {
        std::thread::spawn(move || {
            for _ in 0..20 {
                let s = format!("{}", Utc::now().to_rfc3339());
                let mut l = log2.lock().unwrap();
                write!(write2, "{}", s).unwrap();
                write2.flush().unwrap();
                l.push_back(s);
            }
        });
    }

    let mut previous_timestamp = chrono::MIN_DATE.and_hms(0, 0, 0);
    for _ in 0..40 {
        let data = mux.read()?;
        let text = std::str::from_utf8(data.data).unwrap();
        let timestamp = chrono::DateTime::parse_from_rfc3339(text).unwrap().into();

        {
            let expected = log.lock().unwrap().pop_front().unwrap();
            assert_eq!(expected, text);
        }

        if timestamp <= previous_timestamp {
            println!("{} (out of order)", text);
        } else {
            println!("{}", text);
        }

        previous_timestamp = timestamp;
    }

    Ok(())
}
```

This shows that even though the timestamps are occasionally out of order (because the data source is racy to begin with), the order coming out of the read-side of the mux _does_ match what's logged in the VecDeque:
```
2020-02-06T19:18:15.395140+00:00
2020-02-06T19:18:15.395222+00:00
2020-02-06T19:18:15.395237+00:00
2020-02-06T19:18:15.395250+00:00
2020-02-06T19:18:15.395174+00:00 (out of order)
2020-02-06T19:18:15.395266+00:00
2020-02-06T19:18:15.395279+00:00
2020-02-06T19:18:15.395276+00:00 (out of order)
2020-02-06T19:18:15.395291+00:00
2020-02-06T19:18:15.395299+00:00
2020-02-06T19:18:15.395303+00:00
2020-02-06T19:18:15.395313+00:00
2020-02-06T19:18:15.395316+00:00
2020-02-06T19:18:15.395326+00:00
2020-02-06T19:18:15.395328+00:00
2020-02-06T19:18:15.395365+00:00
2020-02-06T19:18:15.395384+00:00
2020-02-06T19:18:15.395398+00:00
2020-02-06T19:18:15.395410+00:00
2020-02-06T19:18:15.395422+00:00
2020-02-06T19:18:15.395343+00:00 (out of order)
2020-02-06T19:18:15.395440+00:00
2020-02-06T19:18:15.395449+00:00
2020-02-06T19:18:15.395452+00:00
2020-02-06T19:18:15.395510+00:00
2020-02-06T19:18:15.395534+00:00
2020-02-06T19:18:15.395486+00:00 (out of order)
2020-02-06T19:18:15.395549+00:00
2020-02-06T19:18:15.395568+00:00
2020-02-06T19:18:15.395590+00:00
2020-02-06T19:18:15.395603+00:00
2020-02-06T19:18:15.395616+00:00
2020-02-06T19:18:15.395628+00:00
2020-02-06T19:18:15.395641+00:00
2020-02-06T19:18:15.395653+00:00
2020-02-06T19:18:15.395665+00:00
2020-02-06T19:18:15.395677+00:00
2020-02-06T19:18:15.395691+00:00
2020-02-06T19:18:15.395704+00:00
2020-02-06T19:18:15.395716+00:00
```

I may have missed an important detail, of course, and this could also be a false test. 😉

**Comment by lnicola** [comment]
You say that:

> Obviously select/poll is more than capable of preserving relative output within some resolution or else your console wouldn't make any sense with a process writing to both (forget interleaving).

Terminal emulators don't call `select` with the `stdout` and `stderr` file descriptors of their child process. Instead, they use `dup2` to map both of them to a single slave PTY fd and rely on the implicit ordering between `write`s, not unlike what `io-mux` is doing. 

See for example [`ttynew`](https://git.suckless.org/st/file/st.c.html#l753) in https://git.suckless.org/st/file/st.c.html.

**Comment by lnicola** [comment]
@uberjay and others mentioned they get buffer full errors on BSD and MacOS. It works for me on Linux with 4 000 000 messages, but I had to remove the logging because there's a deadlock between the writers and the main thread: `write` can block when it has no space, while the main thread might be blocked waiting on the mutex.

**Comment by lnicola** [comment]
Interestingly, `sendmsg` should also block on FreeBSD: https://www.freebsd.org/cgi/man.cgi?query=sendmsg&apropos=0&sektion=2&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html

CC @Freaky.

**Comment by lnicola** [comment]
Ugh: https://stackoverflow.com/questions/16555101/sendto-dgrams-do-not-block-for-enobufs-on-osx

**Comment by joshtriplett** [comment]
@lnicola Thank you for providing detailed explanations.

@mqudsi As mentioned on Reddit, the code as posted has a race condition in it, and does not demonstrate this issue. io-mux can't introduce a well-defined order when the sending end doesn't have a well-defined order to begin with. The only goal is to provide the same ordering properties that you'd get if you set both stdout and stderr to a single pipe via `dup2`.

**Comment by mqudsi** [comment]
The code sample I posted is mostly\* free of user-space race conditions *in and of itself*: it has two separate threads writing to what would be two separate streams. The raciness is arguably taking place within the abstraction presented by io-mux **and I do not blame it and don't think anything better can be done without locking**; my original point (which I think still stands) is that the result isn't strictly better than what can be accomplished with select/poll (reading from two streams and distinguishing the data), io-mux cannot make any actual, hard guarantees besides "best effort" ordering. If the non-blocking sends can be fixed (I'm not sure if that's possible on all unixes, though) io-mux would still be a nice option on *nix platforms.

Described as a tagging alternative to `dup2`: I agree absolutely. The only difference is that dup2 forces you to "deal" with the raciness of your code in your code, whereas io-mux is in the unfortunate position of being an abstraction around that, which is why I feel it is important for the readme/documentation to be as precise as possible in what this solution can and can't realistically do.

[\*] excepting a thread being paged out after it obtains a timestamp and before it writes.

**Comment by joshtriplett** [comment]
@mqudsi 
> my original point (which I think still stands) is that the result isn't strictly better than what can be accomplished with select/poll (reading from two streams and distinguishing the data), io-mux cannot make any actual, hard guarantees besides "best effort" ordering

io-mux does provide better results than what you can get with two separate streams. It provides results as good as what you can get with *one* stream (such as a single pipe or file for both stdout and stderr using `dup2`, or a single pty as used by a terminal), which is strictly better than what you can get with two streams.

Either io-mux or a single pipe/file/pty will produce results in the order written. If the results get written in an indeterminate order, they'll arrive in an indeterminate order.

> [*] excepting a thread being paged out after it obtains a timestamp and before it writes.

Or, more likely, both threads running simultaneously on different processors, both threads obtaining timestamps (in one order), and then both threads writing (in the other order). That's far more likely to happen.
